# Generated by Django 4.1.1 on 2022-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('history', models.CharField(max_length=500)),
                ('material', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
