# Generated by Django 4.1.1 on 2022-10-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('history', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
