# Generated by Django 4.1.1 on 2022-10-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_coins_delete_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('asking_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='coins',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coins',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='main_app.owner'),
        ),
    ]
