# Generated by Django 4.1.1 on 2022-10-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_coins_owner_owner_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('coins', models.ManyToManyField(to='main_app.coins')),
            ],
        ),
    ]
